Update check license action (#10)
Co-authored-by: Jakob Jensen <jakobj@jakobj.dk>

diff --git a/actions/dotnet-check-license/action.yaml b/actions/dotnet-check-license/action.yaml
--- a/actions/dotnet-check-license/action.yaml
+++ b/actions/dotnet-check-license/action.yaml
@@ -4,7 +4,7 @@ description: Verifies only allowed licenses are in use
 
 inputs:
   project-folder:
-    description: The folder containing the project to check.
+    description: The project folder (not recommended, use a specific file), project file or solution file to check.
     required: true
   allowed-licenses-file:
     description: |
@@ -30,9 +30,19 @@ inputs:
       }
       ```
     required: false
+  license-ignore-file:
+    description: |
+      This file allows for ignoring nuget packages.
+      Example:
+      ```json
+      [
+        "Nuget.Name"
+      ]
+      ```
+    required: false
   tool-version:
-    default: 2.4.0
-    description: The version of the dotnet-project-licenses tool to use
+    default: 3.0.13
+    description: The version of the nuget-license tool to use
     required: false
 
 runs:
@@ -41,15 +51,34 @@ runs:
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
 
-    - name: Install license tool
+    - name: Install nuget-license tool
       shell: bash
-      run: dotnet tool install --global dotnet-project-licenses --version ${{ inputs.tool-version }}
+      run: dotnet tool install --global nuget-license --version ${{ inputs.tool-version }}
 
     - name: Add mapping argument
       shell: bash
       if: inputs.license-mapping-file
-      run: echo "ARGUMENTS=--licenseurl-to-license-mappings ${{ inputs.license-mapping-file }}" >> $GITHUB_ENV
+      run: echo "ARGUMENTS=--licenseurl-to-license-mappings ${{ inputs.license-mapping-file }}" | tee -a $GITHUB_ENV
+
+    - name: Add ignore argument
+      shell: bash
+      if: inputs.license-ignore-file
+      run: echo "ARGUMENTS=--ignored-packages ${{ inputs.license-ignore-file }} ${{ env.ARGUMENTS }}" | tee -a $GITHUB_ENV
+
+    - name: Auto-correct project argument
+      shell: bash
+      run: |
+        if [ -d '${{ inputs.project-folder }}' ]; then
+          file=$(find '${{ inputs.project-folder }}' \( -iname "*.csproj" -o -iname "*.solution" \) | head -n1)
+          if [ -z "$file" ]; then
+            echo "::error::No project was found in '${{ inputs.project-folder }}'."
+            exit 1
+          fi
+          echo "PROJECT=$file" | tee -a $GITHUB_ENV
+        else
+          echo "PROJECT=${{ inputs.project-folder }}" | tee -a $GITHUB_ENV
+        fi
 
     - name: Run license check
       shell: bash
-      run: ~/.dotnet/tools/dotnet-project-licenses -i ${{ inputs.project-folder }} --allowed-license-types ${{ inputs.allowed-licenses-file }} ${{ env.ARGUMENTS }}
+      run: ~/.dotnet/tools/nuget-license --input ${{ env.PROJECT }} --allowed-license-types ${{ inputs.allowed-licenses-file }} ${{ env.ARGUMENTS }}
