grep out the relevant parts

diff --git a/actions/dotnet-validate-solution/action.yaml b/actions/dotnet-validate-solution/action.yaml
--- a/actions/dotnet-validate-solution/action.yaml
+++ b/actions/dotnet-validate-solution/action.yaml
@@ -70,4 +70,14 @@ runs:
       shell: bash
       env:
         version: ""
-      run: dotnet test --no-restore -warnaserror --logger:"console;verbosity=minimal"
+      run: |
+        output=$(dotnet test --no-restore -warnaserror --logger:"console;verbosity=normal")
+
+        echo "$output" | grep -E "Passed!|Failed!"
+
+        if echo "$output" | grep -q "Failed!"; then
+          echo "Failed tests and stack traces:"
+          echo "$output" | grep -A 10 "Failed"
+          exit 1
+        fi
+
